Add handling of a log of type string
hpi-swt2/contacts-portal pull request #148
Opened 2021-01-22 18:06 UTC by Alexander-Dubrawski

There is an issue with the flash messages when logging out. The partial can only handle a dictionary with a heading and message. Somehow we are receiving a string instead of a dictionary while logging out. To fix this issue we simply check the type now. Not the best solution but for now it should work.

2021-01-22 18:15 UTC, LinqLover commented
Seems like a duplicate of 844735d in #120 as announced in the Discord ... 😫

2021-01-22 18:16 UTC, LinqLover commented
Well, let's decide on the better implementation and get it merged soon.

2021-01-22 21:21 UTC, felixauringer requested changes
Not sure if my if-else-end works with the suggestions but you get the idea.  
I still think that these flash messages are hacky. But this fix is more important than refactoring them.

2021-01-22 21:21 UTC, felixauringer commented on app/views/layouts/_flash_messages.html.erb
> +      <% if !log.is_a? String %>
```suggestion
      <% else %>
```

2021-01-22 21:21 UTC, felixauringer commented on app/views/layouts/_flash_messages.html.erb
> +        <% if !log[:heading].nil? %>
```suggestion
        <% if log[:heading].present? %>
```

2021-01-22 21:21 UTC, felixauringer commented on app/views/layouts/_flash_messages.html.erb
>        <% end %>
```suggestion
```

2021-02-03 14:06 UTC, felixauringer commented
Is this PR still worked on?

2021-02-03 20:36 UTC, Alexander-Dubrawski commented
Already fixed in #120

2021-02-03 20:36 UTC, closed without merging