Feature/profile dropdown
hpi-swt2/contacts-portal pull request #57
Opened 2020-12-07 09:37 UTC by konradh

2020-12-07 10:19 UTC, sirkrypt0 requested changes

2020-12-07 10:19 UTC, sirkrypt0 commented on app/views/layouts/_navbar.html.erb
> +                  <%= link_to "Visit my profile", user_path(current_user), class: 'dropdown-item' %>
Use something like the following for internationalization. Make sure to set the corresponding value in `config/locales/en.yml`.

```suggestion
                  <%= link_to I18n.t('menu.visit_profile'), user_path(current_user), class: 'dropdown-item' %>
```

2020-12-07 10:19 UTC, sirkrypt0 commented on app/views/layouts/_navbar.html.erb
> +                  <%= link_to "Edit my profile", edit_user_registration_path(current_user), class: 'dropdown-item' %>
Add internationalization here as well.

2020-12-07 12:02 UTC, frcroth commented on .gitignore
> +/.idea
See https://github.com/hpi-swt2/connections-portal/pull/56#issuecomment-738951815

2020-12-11 09:21 UTC, sirkrypt0 approved these changes

2020-12-11 11:09 UTC, felixauringer approved these changes

2020-12-11 11:10 UTC, frcroth commented on .gitignore
> +/.idea
```suggestion
/.vscode
/.idea
```

2020-12-11 11:12 UTC, frcroth commented on .gitignore
> +/.idea
```suggestion
```

2020-12-11 11:14 UTC, merged